let data = {
	"legend": {
		"data": [{
			"name": "干球设定",
			"textStyle": {
				"color": "#FD0100"
			}
		}, {
			"name": "湿球设定",
			"textStyle": {
				"color": "#00C853"
			}
		}],
		"padding": [20, 80, 10, 80]
	},
	"grid": null,
	"series": [{
		"name": "干球设定",
		"type": "line",
		"stack": null,
		"symbolSize": 1,
		"showAllSymbol": true,
		"data": [{
			"value": "82.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "82.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "83.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "84.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "85.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "85.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "85.00",
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "35",
				"offset": [0, 0]
			}
		}, {
			"value": "85.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "85.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "85.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "86.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "87.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "38",
				"offset": [0, 0]
			}
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "88.80",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "89.60",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "90.40",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "91.20",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "92.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "92.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "92.00",
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "42",
				"offset": [0, 0]
			}
		}, {
			"value": "92.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "92.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "92.60",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "93.20",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "93.80",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "94.40",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "95.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "95.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "95.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "95.00",
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "45",
				"offset": [0, 0]
			}
		}, {
			"value": "95.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "95.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "95.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "95.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "96.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "96.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "97.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "97.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "98.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "98.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "98.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "98.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "98.00",
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "48",
				"offset": [0, 0]
			}
		}, {
			"value": "98.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "98.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "98.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "98.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "98.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "99.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "99.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "100.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "100.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "101.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "101.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "102.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "102.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "103.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "103.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "104.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "104.00",
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "54",
				"offset": [0, 0]
			}
		}, {
			"value": "104.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "104.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "104.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "105.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "105.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "106.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "106.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "107.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "107.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "108.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "108.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "109.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "109.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "110.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "110.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "111.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "112.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "113.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "114.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "115.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "115.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "116.25",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "117.50",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "118.75",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "70",
				"offset": [0, 0]
			}
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}, {
			"value": "120.00",
			"symbolSize": 0,
			"label": null
		}],
		"itemStyle": {
			"normal": {
				"color": "#FD0100"
			}
		},
		"lineStyle": {
			"normal": {
				"color": "#FD0100"
			}
		}
	}, {
		"name": "湿球设定",
		"type": "line",
		"stack": null,
		"symbolSize": 1,
		"showAllSymbol": true,
		"data": [{
			"value": 32,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 32.00,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 33.00,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 34.00,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 35,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 35,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 35,
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": null,
				"offset": [0, 0]
			}
		}, {
			"value": 35,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 35,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 35.00,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 35.33,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 35.66,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": null,
				"offset": [0, 0]
			}
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36.00,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36.17,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36.34,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36.51,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36.68,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 36.85,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 37.02,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 37.19,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 37.36,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 37.53,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 37.70,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 37.87,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 38,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 38.00,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 38.60,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 39.20,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 39.80,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 40.40,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 41,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 41.00,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 41.25,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 41.50,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 41.75,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": null,
				"offset": [0, 0]
			}
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}, {
			"value": 42,
			"symbolSize": 0,
			"label": null
		}],
		"itemStyle": {
			"normal": {
				"color": "#00C853"
			}
		},
		"lineStyle": {
			"normal": {
				"color": "#00C853"
			}
		}
	}, {
		"name": "工艺曲线段",
		"type": "line",
		"stack": null,
		"symbolSize": 1,
		"showAllSymbol": true,
		"data": [{
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "1",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "3",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "5",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "3",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "48",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "5",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "4",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "5",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "6",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "6",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "8",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "12",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "3",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "12",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "1",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "5",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "1",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "4",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": {
				"show": true,
				"distance": 0,
				"formatter": "(时长设定h)\n\n30",
				"offset": [0, 0]
			}
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}, {
			"value": 10,
			"symbolSize": 1,
			"label": null
		}],
		"itemStyle": {
			"normal": {
				"color": "#ffffff"
			}
		},
		"lineStyle": {
			"normal": {
				"color": "#ffffff"
			}
		}
	}],
	"xaxis": {
		"type": null,
		"axisTick": null,
		"offset": 0,
		"axisLabel": {
			"textStyle": null,
			"padding": null,
			"showMinLabel": true,
			"showMaxLabel": true
		},
		"axisLine": null,
		"boundaryGap": false,
		"data": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
			27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
			52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
			77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
			101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
			121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
			141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160,
			161, 162
		],
		"symbol": "none"
	},
	"xdata": [1, 4, 9, 12, 60, 65, 69, 74, 80, 86, 94, 106, 109, 121, 122, 127, 128, 132, 162, 162],
	"ydescription": ["第1恒温烤段 共1小时", "第2升温烤段 共3小时", "第3恒温烤段 共5小时", "第4升温烤段 共3小时", "第5恒温烤段 共48小时", "第6升温烤段 共5小时",
		"第7恒温烤段 共4小时", "第8升温烤段 共5小时", "第9恒温烤段 共6小时", "第10升温烤段 共6小时", "第11恒温烤段 共8小时", "第12升温烤段 共12小时",
		"第13恒温烤段 共3小时", "第14升温烤段 共12小时", "第15恒温烤段 共1小时", "第16升温烤段 共5小时", "第17恒温烤段 共1小时", "第18升温烤段 共4小时",
		"第19恒温烤段 共30小时", ""
	],
	"yaxis": null
}
module.exports = {
	data: data
}
